### PR TITLE
add stagedOnly flag

### PR DESCRIPTION
**Pull request by evertbouw**
closes https://github.com/cschroeter/ts-strictify/issues/3

### CODE REVIEW

**Comment by cschroeter** [comment]
Thank you for your submission 🚀.
I will have a look at this PR as soon as I have come up with at least a basic test setup to ensure that further changes will not break the expected behavior of this library. So we can have this feature available at end of this week :)

**Comment by ruanyl** [comment]
Any updates to this PR? @cschroeter

**Comment by shaungrady** [comment]
Would love this option.

**Comment by cschroeter** [comment]
Solved in 1.4

**Pull request closed without merging**
